# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd338de44247e65fd44f6e8fec99c5651057ce8fd4a57693be5dca13e63bfe9515a2cc1ae0169f1e05ad67864ac4bd88fa28073fa56ebec0e9f903326f8ee71d
  sendgrid_smtp:
    :authentication: "plain"
    :address: "smtp.sendgrid.net"
    :port: 587
    :domain: "example.com"
    :user_name: "apikey"
    :password: <%= ENV['SENDGRID_KEY'] %>
    :enable_starttls_auto: true
  amazon_smtp:
    :authentication: "plain"
    :address: "email-smtp.us-west-2.amazonaws.com"
    :port: 587
    :domain: "zzz.com"
    :user_name: <%= ENV['AMAZON_SES_USER'] %>
    :password: <%= ENV['AMAZON_SES_KEY'] %>
    :enable_starttls_auto: true

test:
  secret_key_base: 3ae56700325639fab0e89478fde63582565dd7ce37df46d88ba22a0c54500ee913ef6b958a8273e6e3dbd8963cc77fcf83bdeb49775687e3122869daf508bf08
  sendgrid_smtp:
    :authentication: "plain"
    :address: "smtp.sendgrid.net"
    :port: 587
    :domain: "example.com"
    :user_name: "apikey"
    :password: <%= ENV['SENDGRID_KEY'] %>
    :enable_starttls_auto: true
  amazon_smtp:
    :authentication: "plain"
    :address: "email-smtp.us-west-2.amazonaws.com"
    :port: 587
    :domain: "zzz.com"
    :user_name: <%= ENV['AMAZON_SES_USER'] %>
    :password: <%= ENV['AMAZON_SES_KEY'] %>
    :enable_starttls_auto: true

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid_smtp:
    :authentication: "plain"
    :address: "smtp.sendgrid.net"
    :port: 587
    :domain: "example.com"
    :user_name: "apikey"
    :password: <%= ENV['SENDGRID_KEY'] %>
    :enable_starttls_auto: true
  amazon_smtp:
    :authentication: "plain"
    :address: "email-smtp.us-west-2.amazonaws.com"
    :port: 587
    :domain: "zzz.com"
    :user_name: "AKIAJPDVM6VFNC4FWX2A"
    :password: <%= ENV['AMAZON_SES_KEY'] %>
    :enable_starttls_auto: true
